### ISSUE TITLE
Packages files (tgz) get written with 0 bytes on minio

### ISSUE THREAD

**Issue by arthmoeros** [barolab/verdaccio-minio#12]
Hello,

I tried to use this plugin, although I wouldn't know if this is a minio-js issue, this plugin's or a combination of both.

Tested with the docker compose example on the npmjs site at https://www.npmjs.com/package/verdaccio-minio

Also tested with a custom verdaccio image with `npm install verdaccio-minio` beforehand (using verdaccio 4.2), got same results (also tested with 4.3.5).

The package.json files are written OK, but the published tgz files are put on minio with 0 bytes

Also tried (somehow) with the docker-compose-4.3.yml example on this same repo, but verdaccio 4.3 doesn't even detect the plugin.

PS: I forgot to mention, used the same configuration example as shown in the README.

PS n°2: I tested proxying lodash from npmjs repo, the tgz file was created correctly, so I guess is a publish issue.

**Comment by barolab** [comment]
Hi @arthmoeros,
Seems a bit odd. It points a missing integration test for the package publishing feature. I'll add a new test case for this in order to try reproducing your issue.
In the meantime, can you give me some debugging informations (logs) ? And provide the package.json you use to publish your package ?

**Comment by barolab** [comment]
I added an integration test in #15 to make sure this won't happen again

**Comment by arthmoeros** [comment]
> Hi @arthmoeros,
> Seems a bit odd. It points a missing integration test for the package publishing feature. I'll add a new test case for this in order to try reproducing your issue.
> In the meantime, can you give me some debugging informations (logs) ? And provide the package.json you use to publish your package ?

I just saw this, Do you still need the log?, I can reproduce the issue and provide you the info you need but since I already submitted a PR fixing this and you merged it I was wondering.

**Comment by barolab** [comment]
Not necessary now, I was able to reproduce the bug locally. Thanks for the PR though.
